#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

if ! command -v circom &>/dev/null; then
  echo "circom not found. Install circom 2.2.3 from https://docs.circom.io/getting-started/installation/" >&2
  exit 1
fi

version=$(circom --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
if [[ -z "$version" ]]; then
  echo "Could not parse circom version. Install circom 2.2.3 from https://docs.circom.io/getting-started/installation/" >&2
  exit 1
fi

# ── Pinned-version assertion (issue #535) ─────────────────────────────────────
# The committed verification_key.json and constraints.json were produced with
# the circom version recorded in circuits/config.json. Assert equality, not
# just ">= 2.1.6": a different circom can emit a different witness layout or
# constraint count while still passing, which would silently break the
# on-chain verifier against proofs generated by the client.
pinned=$(node -e "console.log(require('./config.json').circomVersion || '')")
if [[ -z "$pinned" ]]; then
  echo "No circomVersion recorded in circuits/config.json. Set it to the version" >&2
  echo "used to produce the committed artifacts (e.g. 2.2.3) and re-run setup." >&2
  exit 1
fi
if [[ "$version" != "$pinned" ]]; then
  echo "circom $version detected; the committed artifacts were built with circom $pinned." >&2
  echo "A different circom can silently change the constraint count or witness" >&2
  echo "layout. Install circom $pinned (see README) or update circuits/config.json" >&2
  echo "circomVersion alongside a full recompile + re-setup + key rotation." >&2
  exit 1
fi
echo "circom $version matches the pinned version in circuits/config.json."

# Regenerate membership.circom from membership.template.circom + config.json
# Allow overriding the levels with the LEVELS env var, e.g.:
#
#   LEVELS=8 npm run compile
#
echo "Generating membership.circom (LEVELS=${LEVELS:-from config.json})"
node scripts/gen-circuit.cjs

mkdir -p build
circom membership.circom --r1cs --wasm --sym --prime bls12381 -l ../node_modules -o build

echo "Compiled -> build/membership.r1cs, build/membership_js/membership.wasm"
