#!/usr/bin/env bash
# Powers-of-Tau (bls12381) + Groth16 trusted setup for the Sharibo circuit.
#
# This is a hackathon-demo trusted setup: single contributor, random entropy
# from /dev/urandom. Real deployments would run a multi-party ceremony. See
# README "Honest limitations".
#
# After a successful run this script appends a fingerprint entry to
# circuits/SETUP_TRANSCRIPT.md so the canonical artifacts are always
# traceable.  ⚠️  Re-running setup produces a NEW verification key —
# any on-chain circle created with the previous vk will be permanently
# incompatible with proofs generated by the new key.
#
# Safety checks built in (issue #271):
#   * `snarkjs zkey verify` validates the final zkey against the r1cs and the
#     powers-of-tau file, so a corrupted or mismatched key fails the run
#     before it can be baked into a deployed circle's VerificationKey.
#   * If the regenerated verification key differs from the committed
#     circuits/verification_key.json, the script refuses to proceed silently:
#     that difference is a key rotation, so it must be acknowledged with
#     ALLOW_KEY_ROTATION=1.
set -euo pipefail
cd "$(dirname "$0")/.."

BUILD=build
CURVE=bls12381
PTAU_POWER=12
PTAU_FINAL="$BUILD/pot${PTAU_POWER}_${CURVE}_final.ptau"
TRANSCRIPT="SETUP_TRANSCRIPT.md"

mkdir -p "$BUILD"

if [ ! -f "$BUILD/membership.r1cs" ]; then
  echo "membership.r1cs not found — run scripts/compile.sh first" >&2
  exit 1
fi

# Snapshot the committed canonical verification key before we overwrite it,
# so we can tell a silent regeneration apart from a deliberate rotation.
if [ -f verification_key.json ]; then
  cp verification_key.json "$BUILD/.verification_key.previous.json"
fi

if [ ! -f "$PTAU_FINAL" ]; then
  npx --yes snarkjs powersoftau new "$CURVE" "$PTAU_POWER" "$BUILD/pot${PTAU_POWER}_${CURVE}_0000.ptau" -v
  npx --yes snarkjs powersoftau contribute "$BUILD/pot${PTAU_POWER}_${CURVE}_0000.ptau" "$BUILD/pot${PTAU_POWER}_${CURVE}_0001.ptau" \
    --name="Sharibo phase1 contribution" -v -e="$(head -c 64 /dev/urandom | base64)"
  npx --yes snarkjs powersoftau prepare phase2 "$BUILD/pot${PTAU_POWER}_${CURVE}_0001.ptau" "$PTAU_FINAL" -v
fi

# ── Existing-key check + fast path (issue #271) ───────────────────────────────
# If a final zkey already exists it is verified BEFORE anything is regenerated:
# a deliberately corrupted or mismatched key must fail the run instead of being
# silently overwritten. And if a *valid* key already exports exactly the
# committed verification key, the ceremony is skipped entirely — re-running it
# would only produce a different key. (This is what keeps `just circuits`
# idempotent.)
if [ -f "$BUILD/membership_final.zkey" ]; then
  echo "Verifying existing build/membership_final.zkey against r1cs + ptau..."
  if ! npx --yes snarkjs zkey verify "$BUILD/membership.r1cs" "$PTAU_FINAL" "$BUILD/membership_final.zkey"; then
    echo "" >&2
    echo "✗ Existing build/membership_final.zkey is corrupted or was built from a" >&2
    echo "  different circuit / powers-of-tau. Rebuild it deliberately:" >&2
    echo "      rm build/membership_final.zkey && npm run setup" >&2
    echo "" >&2
    exit 1
  fi

  TMP_VK="$BUILD/.verification_key.fastpath.json"
  npx --yes snarkjs zkey export verificationkey "$BUILD/membership_final.zkey" "$TMP_VK"
  if cmp -s "$TMP_VK" verification_key.json; then
    rm -f "$TMP_VK"
    echo "Existing build/membership_final.zkey is valid and matches the committed"
    echo "verification_key.json — nothing to regenerate. To force a rotation:"
    echo "    rm build/membership_final.zkey && ALLOW_KEY_ROTATION=1 npm run setup"
    exit 0
  fi
  rm -f "$TMP_VK"
  echo "Existing zkey is valid but exports a different key than the committed one — regenerating."
fi

npx --yes snarkjs groth16 setup "$BUILD/membership.r1cs" "$PTAU_FINAL" "$BUILD/membership_0000.zkey"
npx --yes snarkjs zkey contribute "$BUILD/membership_0000.zkey" "$BUILD/membership_final.zkey" \
  --name="Sharibo circuit key contribution" -v -e="$(head -c 64 /dev/urandom | base64)"

# ── Final-key integrity check (issue #271) ────────────────────────────────────
# Verifies the final zkey is a self-consistent Groth16 key for *this* r1cs
# under *this* powers-of-tau file. Non-zero exit aborts the script (set -e),
# which is the only automated guard against baking a corrupted or mismatched
# key into a deployed circle's VerificationKey.
npx --yes snarkjs zkey verify "$BUILD/membership.r1cs" "$PTAU_FINAL" "$BUILD/membership_final.zkey"

npx --yes snarkjs zkey export verificationkey "$BUILD/membership_final.zkey" verification_key.json

# ── Committed-key divergence guard (issue #271) ───────────────────────────────
# Every `zkey contribute` consumes fresh /dev/urandom entropy, so a re-run
# essentially always yields a different verification key. When that happens
# the old key is no longer canonical: any deployed circle pinned the old vk
# and will reject new proofs. Refuse to overrun the committed key silently —
# the operator must acknowledge the rotation explicitly.
if [ -f "$BUILD/.verification_key.previous.json" ] \
  && ! cmp -s "$BUILD/.verification_key.previous.json" verification_key.json; then
  if [ "${ALLOW_KEY_ROTATION:-}" != "1" ]; then
    echo "" >&2
    echo "⚠️  Regenerated verification key differs from committed circuits/verification_key.json." >&2
    echo "    This is a key rotation (not a silent regeneration). Re-run with" >&2
    echo "    ALLOW_KEY_ROTATION=1 to acknowledge it, or restore the committed key with" >&2
    echo "    'git checkout circuits/verification_key.json'." >&2
    echo "" >&2
    exit 1
  fi
  echo ""
  echo "⚠️  Key rotation acknowledged (ALLOW_KEY_ROTATION=1) — the new verification key" >&2
  echo "    will be recorded in the transcript below." >&2
  echo "" >&2
else
  echo "Verification key unchanged from committed circuits/verification_key.json."
fi

hash_file() {
  # Portable SHA-256: prefer sha256sum (Linux/WSL), fall back to shasum (macOS).
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    echo "sha256-unavailable"
  fi
}

hash_file verification_key.json > verification_key.json.sha256
hash_file "$BUILD/membership_js/membership.wasm" > membership.wasm.sha256
hash_file "$BUILD/membership_final.zkey" > membership_final.zkey.sha256

echo "Setup complete -> build/membership_final.zkey, verification_key.json"

# ── Transcript fingerprinting ────────────────────────────────────────────────
# snarkjs has no --version flag (it prints usage and exits non-zero); npx
# resolves the local node_modules/.bin/snarkjs, whose first output line is
# "snarkjs@<version>".
SNARKJS_VERSION="$(npx --yes snarkjs --version 2>&1 | head -n1 | sed 's/snarkjs@//' || true)"
DATE_NOW="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

HASH_VK="$(hash_file verification_key.json)"
HASH_ZKEY="$(hash_file "$BUILD/membership_final.zkey")"
HASH_PTAU="$(hash_file "$PTAU_FINAL")"

# Create the transcript file with a header if it doesn't exist yet.
if [ ! -f "$TRANSCRIPT" ]; then
cat > "$TRANSCRIPT" << 'HEADER'
# Sharibo Trusted-Setup Transcript

Each entry below records one ceremony run.  The **verification key hash** is
the authoritative fingerprint: it must match `shasum -a 256 verification_key.json`
(or `sha256sum verification_key.json` on Linux) for any set of local artifacts
to be considered canonical.

> ⚠️ **A new `setup.sh` run produces a brand-new verification key.**
> Any on-chain circle created with a previous vk stores that old key
> inside its contract state (written at `create_circle` time).  Proofs
> generated from the new key will **fail** to verify against those circles.
> All existing circles must be cancelled and recreated after a key rotation.

---

HEADER
fi

# Append the new entry.
cat >> "$TRANSCRIPT" << ENTRY
## Entry — $DATE_NOW

| Field              | Value |
|--------------------|-------|
| Date (UTC)         | \`$DATE_NOW\` |
| snarkjs version    | \`$SNARKJS_VERSION\` |
| Curve              | \`$CURVE\` |
| Powers-of-Tau power | $PTAU_POWER |
| \`verification_key.json\` SHA-256 | \`$HASH_VK\` |
| \`membership_final.zkey\` SHA-256  | \`$HASH_ZKEY\` |
| \`${PTAU_FINAL##*/}\` SHA-256  | \`$HASH_PTAU\` |

> Note: \`membership_final.zkey\` and the ptau file are **not committed** to the
> repository (they are large binary files listed in .gitignore).  Only
> \`verification_key.json\` and this transcript are committed.  To verify
> locally, rerun \`scripts/compile.sh && scripts/setup.sh\` and compare the
> \`verification_key.json\` hash against the entry above.

---

ENTRY

echo "Transcript appended -> $TRANSCRIPT"
echo "  verification_key.json SHA-256: $HASH_VK"
